-- Create table for Elyano
CREATE TABLE public.pipeline_prospec_elyano (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato smallint,
  mensagem_enviada smallint,
  conexao smallint,
  whatsapp_obtido smallint,
  reuniao_agendada smallint,
  reuniao_realizada smallint,
  data_atualizacao date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create table for Marcos Rossi
CREATE TABLE public.pipeline_prospec_marcos_rossi (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato smallint,
  mensagem_enviada smallint,
  conexao smallint,
  whatsapp_obtido smallint,
  reuniao_agendada smallint,
  reuniao_realizada smallint,
  data_atualizacao date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Create table for BP Results
CREATE TABLE public.pipeline_prospec_bp_results (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contato smallint,
  mensagem_enviada smallint,
  conexao smallint,
  whatsapp_obtido smallint,
  reuniao_agendada smallint,
  reuniao_realizada smallint,
  data_atualizacao date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Enable Row Level Security for all tables
ALTER TABLE public.pipeline_prospec_elyano ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_prospec_marcos_rossi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pipeline_prospec_bp_results ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for pipeline_prospec_elyano
CREATE POLICY "Permitir leitura pública de métricas" 
ON public.pipeline_prospec_elyano 
FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserção pública de métricas" 
ON public.pipeline_prospec_elyano 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir atualização pública de métricas" 
ON public.pipeline_prospec_elyano 
FOR UPDATE 
USING (true);

-- Create RLS policies for pipeline_prospec_marcos_rossi
CREATE POLICY "Permitir leitura pública de métricas" 
ON public.pipeline_prospec_marcos_rossi 
FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserção pública de métricas" 
ON public.pipeline_prospec_marcos_rossi 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir atualização pública de métricas" 
ON public.pipeline_prospec_marcos_rossi 
FOR UPDATE 
USING (true);

-- Create RLS policies for pipeline_prospec_bp_results
CREATE POLICY "Permitir leitura pública de métricas" 
ON public.pipeline_prospec_bp_results 
FOR SELECT 
USING (true);

CREATE POLICY "Permitir inserção pública de métricas" 
ON public.pipeline_prospec_bp_results 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir atualização pública de métricas" 
ON public.pipeline_prospec_bp_results 
FOR UPDATE 
USING (true);

-- Create triggers for automatic timestamp updates
CREATE TRIGGER update_pipeline_prospec_elyano_updated_at
  BEFORE UPDATE ON public.pipeline_prospec_elyano
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_pipeline_prospec_marcos_rossi_updated_at
  BEFORE UPDATE ON public.pipeline_prospec_marcos_rossi
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_pipeline_prospec_bp_results_updated_at
  BEFORE UPDATE ON public.pipeline_prospec_bp_results
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();