-- Create pipeline_prospec_elam table with same structure as pipeline_prospec_elyano
CREATE TABLE public.pipeline_prospec_elam (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  contato smallint DEFAULT NULL,
  mensagem_enviada smallint DEFAULT NULL,
  conexao smallint DEFAULT NULL,
  whatsapp_obtido smallint DEFAULT NULL,
  reuniao_agendada smallint DEFAULT NULL,
  reuniao_realizada smallint DEFAULT NULL,
  data_atualizacao date DEFAULT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  meta_mensagens_enviadas integer DEFAULT 0,
  meta_reunioes_agendadas integer DEFAULT 0,
  meta_reunioes_realizadas integer DEFAULT 0,
  data_inicio date DEFAULT NULL,
  data_fim date DEFAULT NULL
);

-- Enable Row Level Security
ALTER TABLE public.pipeline_prospec_elam ENABLE ROW LEVEL SECURITY;

-- Create RLS policies (same as other prospection tables)
CREATE POLICY "Allow public insert" 
ON public.pipeline_prospec_elam 
FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow public update" 
ON public.pipeline_prospec_elam 
FOR UPDATE 
USING (true);

CREATE POLICY "Allow public select" 
ON public.pipeline_prospec_elam 
FOR SELECT 
USING (true);

CREATE POLICY "Allow public delete" 
ON public.pipeline_prospec_elam 
FOR DELETE 
USING (true);

-- Create trigger for updated_at
CREATE TRIGGER update_pipeline_prospec_elam_updated_at
BEFORE UPDATE ON public.pipeline_prospec_elam
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Create trigger to copy goals from previous records
CREATE TRIGGER copy_goals_pipeline_prospec_elam
BEFORE INSERT ON public.pipeline_prospec_elam
FOR EACH ROW
EXECUTE FUNCTION public.copy_prospecting_goals();